baseurl = "http://touch-star.com/"
languageCode = "zh-CN"
title = "TouchStar"
theme = "hugo-cards"
themesDir = "themes/"
paginate = 6
publishDir = "docs"

[params]
  builtBy = "CheneyIn"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = ""
  github = "https://github.com/Ynoy"
  email = "xy410257@163.com"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "CheneyIn"
     link = "http://touch-star.com"

